# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: mylittleci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Nox
      run: |
        python -m pip install --upgrade pip
        pip install nox

    - name: Linting
      run: |
        nox -s linting
    - name: Formatting
      run: |
        nox -s formatting
    - name: Find uncalled/dead code
      run: |
        nox -s dead_code_search
    - name: Static type checking
      run: |
        nox -s static_type_checking
    - name: Test with pytest
      run: |
        nox -s tests
    - name: Build docs
      run: |
        nox -s build_docs

    - name: Store wheel
      uses: actions/upload-artifact@v1
      with:
        name: wheel-${{ matrix.python-version }}
        path: dist

    - name: Store docs
      uses: actions/upload-artifact@v1
      with:
        name: docs-${{ matrix.python-version }}
        path: docs/_build/html

    - name: Store coverage report
      uses: actions/upload-artifact@v1
      with:
        name: coverage-${{ matrix.python-version }}
        path: html_cov

    - name: Store static type checking report
      uses: actions/upload-artifact@v1
      with:
        name: mypy-${{ matrix.python-version }}
        path: html_mypy
